### PR TITLE
omitted log

### PR DESCRIPTION
**Pull request by behzad-ahmadi**

### CODE REVIEW

**Comment by saeedrahimi** [comment]
Thanks for your contribution, I just updated the repository, I assume this issue will be also resolved with the latest changes.
Please feel free to reopen this PR. 🙂

**Comment by behzad-ahmadi** [comment]
Thank you, but there is a problem.

My project includes antd version 4.24.14, and the updated version of "antd-jalali" is not compatible with this. Could you please update the "antd-jalali" version 1.0.3 as well?

@saeedrahimi

**Comment by saeedrahimi** [comment]
@behzad-ahmadi, please checkout [the latest releases:](https://github.com/saeedrahimi/antd-jalali/releases)

- v2.0.1 to support ant-design v5
- v1.4.3 to support ant-design v4

Please feel free to open a new issue if you face any problem 🙂

**Comment by behzad-ahmadi** [comment]
@saeedrahimi 

image


Is there any solution? I can't update the react version.
"react": "^17.0.2",

**Pull request closed without merging**
